export var ResponsiveVoiceLanguages = {
  "en" : "UK English Female",
  "es" : "Spanish Female",
  "fr" : "French Female",
  "de" : "Deutsch Female",
  "it" : "Italian Female",
  "el" : "Greek Female",
  "hu" : "Hungarian Female",
  "tr" : "Turkish Female",
  "ru" : "Russian Female",
  "nl" : "Dutch Female",
  "sv" : "Swedish Female",
  "no" : "Norwegian Female",
  "ja" : "Japanese Female",
  "ko" : "Korean Female",
  "zh" : "Chinese Female",
  "hi" : "Hindi Female",
  "sr" : "Serbian Male",
  "hr" : "Croatian Male",
  "bs" : "Bosnian Male",
  "ro" : "Romanian Male",
  "ca" : "Catalan Male",
  "fi" : "Finnish Female",
  "af" : "Afrikaans Male",
  "sq" : "Albanian Male",
  "ar" : "Arabic Male",
  "hy" : "Armenian Male",
  "cs" : "Czech Female",
  "da" : "Danish Female",
  "eo" : "Esperanto Male",
  "ht" : "Hatian Creole Female",
  "is" : "Icelandic Male",
  "id" : "Indonesian Female",
  "la" : "Latin Female",
  "lv" : "Latvian Male",
  "mk" : "Macedonian Male",
  "mo" : "Moldavian Male",
  "pl" : "Polish Female",
  "pt" : "Portuguese Female",
  "sh" : "Serbo-Croatian Male",
  "sk" : "Slovak Female",
  "sw" : "Swahili Male",
  "ta" : "Tamil Male",
  "th" : "Thai Female",
  "vi" : "Vietnamese Male",
  "cy" : "Welsh Male"
}
