export var bingLanguages = {
  'Arabic': 'ar',
  'Bosnian (Latin)': 'bs-Latn',
  'Bulgarian': 'bg',
  'Catalan': 'ca',
  'Chinese Simplified': 'zh-CHS',
  'Chinese Traditional': 'zh-CHT',
  'Croatian': 'hr',
  'Czech': 'cs',
  'Danish': 'da',
  'Dutch': 'nl',
  'English': 'en',
  'Estonian': 'et',
  'Finnish': 'fi',
  'French': 'fr',
  'German': 'de',
  'Greek': 'el',
  'Haitian Creole': 'ht',
  'Hebrew': 'he',
  'Hindi': 'hi',
  'Hmong Daw': 'mww',
  'Hungarian': 'hu',
  'Indonesian': 'id',
  'Italian': 'it',
  'Japanese': 'ja',
  'Kiswahili': 'sw',
  'Klingon': 'tlh',
  'Klingon (pIqaD)': 'tlh-Qaak',
  'Korean': 'ko',
  'Latvian': 'lv',
  'Lithuanian': 'lt',
  'Malay': 'ms',
  'Maltese': 'mt',
  'Norwegian': 'no',
  'Persian': 'fa',
  'Polish': 'pl',
  'Portuguese': 'pt',
  'Queretaro Otomi': 'otq',
  'Romanian': 'ro',
  'Russian': 'ru',
  'Serbian (Cyrillic)': 'sr-Cyrl',
  'Serbian (Latin)': 'sr-Latn',
  'Slovak': 'sk',
  'Slovenian': 'sl',
  'Spanish': 'es',
  'Swedish': 'sv',
  'Thai': 'th',
  'Turkish': 'tr',
  'Ukrainian': 'uk',
  'Urdu': 'ur',
  'Vietnamese': 'vi',
  'Welsh': 'cy',
  'Yucatec Maya': 'yua'
}

export var yandexLanguages = {
  Albanian: 'sq',
  Arabian: 'ar',
  Armenian: 'hy',
  Azeri: 'az',
  Belarusian: 'be',
  Bosnian: 'bs',
  Bulgarian: 'bg',
  Catalan: 'ca',
  Croatian: 'hr',
  Czech: 'cs',
  Chinese: 'zh',
  Danish: 'da',
  Dutch: 'nl',
  English: 'en',
  Estonian: 'et',
  Finnish: 'fi',
  French: 'fr',
  Georgian: 'ka',
  German: 'de',
  Greek: 'el',
  Hebrew: 'he',
  Hungarian: 'hu',
  Icelandic: 'is',
  Indonesian: 'id',
  Italian: 'it',
  Japanese: 'ja',
  Korean: 'ko',
  Latvian: 'lv',
  Lithuanian: 'lt',
  Macedonian: 'mk',
  Malay: 'ms',
  Maltese: 'mt',
  Norwegian: 'no',
  Polish: 'pl',
  Portuguese: 'pt',
  Romanian: 'ro',
  Russian: 'ru',
  Spanish: 'es',
  Serbian: 'sr',
  Slovak: 'sk',
  Slovenian: 'sl',
  Swedish: 'sv',
  Thai: 'th',
  Turkish: 'tr',
  Ukrainian: 'uk',
  Vietnamese: 'vi'
}
